version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pneumonia-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - pneumonia-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pneumonia-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pneumonia-network

networks:
  pneumonia-network:
    driver: bridge